[project]
name = "pwdgen"
authors = [
    { name = "Bryce Drennan", email = "pwdgen@python.brycedrennan.com" }
]

[tool.maturin]
#python-source = "python"
#module-name = "pwdgen._pwdgen"
module-name = "pwdgen"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

